name: Build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install Visual C++ for Python 2.7
        if: runner.os == 'Windows'
        run: choco install vcpython27 -f -y

      - name: Build wheels
        uses: joerick/cibuildwheel@v1.10.0
        env:
           CIBW_BEFORE_BUILD: cd portaudio-v19 && ./configure && make install
           CIBW_SKIP: pp*
           CIBW_TEST_COMMAND: python {package}/test/wheel_test.py

      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl
